stages:
- init
- build
- release

init:
  stage: init
  when:  manual
  script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - make init

.template: &env-info
  before_script:
  - env | grep -e CARGO -e CI_COMMIT -e CI_PIPELINE
  - cargo -vV
  - rustc -vV
  - rustup show
  - bash --version

build-node:
  <<: *env-info
  stage: build
  script:
  - make build
  - make test

build-contract:
  <<: *env-info
  stage: build
  script:
  - cd erc721
  - cargo-contract --version
  - make build

release-node:
  <<: *env-info
  stage: release
  when: manual
  script:
  - make release
  - docker login -u kirillt -p $DOCKERHUB_TOKEN
  - docker tag supply-chain wivt/supply-chain:$CI_COMMIT_SHORT_SHA 
  - docker tag supply-chain wivt/supply-chain:latest
  - docker push wivt/supply-chain:$CI_COMMIT_SHORT_SHA 
  - docker push wivt/supply-chain:latest

release-contract:
  <<: *env-info
  stage: release
  when: manual
  script:
  - cd erc721
  - make release
  - docker login -u kirillt -p $DOCKERHUB_TOKEN
  - docker tag supply-chain-erc721 wivt/supply-chain-erc721:$CI_COMMIT_SHORT_SHA 
  - docker tag supply-chain-erc721 wivt/supply-chain-erc721:latest
  - docker push wivt/supply-chain-erc721:$CI_COMMIT_SHORT_SHA 
  - docker push wivt/supply-chain-erc721:latest
