stages:
- init
- build
- test
- release

init:
  stage: init
  when:  manual
  script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - make init

.template: &env-info
  before_script:
  - env | grep -e CARGO -e CI_COMMIT -e CI_PIPELINE
  - cargo -vV
  - rustc -vV
  - rustup show
  - bash --version

build:
  <<: *env-info
  stage: build
  script:
  - make build

test:
  <<: *env-info
  stage: test
  script:
  - make test

release:
  <<: *env-info
  stage: release
  when: manual
  script:
  - make release
  - docker login -u kirillt -p $DOCKERHUB_TOKEN
  - docker tag supply-chain wivt/supply-chain:$CI_COMMIT_SHORT_SHA 
  - docker tag supply-chain wivt/supply-chain:latest
  - docker push wivt/supply-chain:$CI_COMMIT_SHORT_SHA 
  - docker push wivt/supply-chain:latest
