stages:
- init
- check
- build

init:
  stage: init
  when:  manual
  script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - make init

build:
  stage: build
  only:
  - master
  script:
  - env | grep -e CARGO -e CI_COMMIT -e CI_PIPELINE
  - cargo -vV
  - rustc -vV
  - rustup show
  - bash --version
  - make build
  - make test
